spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surviversms1?currentSchema=blogservice
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: blog-service

server:
  port: 42773

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9595/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
