spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: blog-service


server:
  port: 42773

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9595/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30




hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
